export { default as ClassWatcher } from './ClassWatcher'
export { default as getRangeFromSelection } from './getRangeFromSelection'
export { default as getRangeFromElement } from './getRangeFromElement'
export { default as isDescendant } from './isDescendant'
export { default as isElement } from './isElement'
export { default as injectScriptToDOM } from './injectScriptToDOM'
